modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "diamondsauctionhouse"
version = "${version}"
displayName = "Diamond Auction House"
authors = "IAmSneak"
description = '''
Adds an Auction House for the diamond economy mod
'''
logoFile = "icon.png"

[[dependencies.diamondsauctionhouse]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.diamondsauctionhouse]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.diamondsauctionhouse]]
modId = "diamondeconomy"
mandatory = true
versionRange = "[1.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.diamondsauctionhouse]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.2.57,)"
ordering = "NONE"
side = "BOTH"